export const cartActionTypes = {
  TOGGLE_CART: "TOGGLE_CART",
  CLOSE_CART: "CLOSE_CART",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_ITEM_FROM_CART: "REMOVE_ITEM_FROM_CART",
  REDUCE_CART_ITEM_QUANTITY: "REDUCE_CART_ITEM_QUANTITY",
};
