const userActionTypes = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  SET_CURRENT_USER_SIGN_IN_ERROR: "SET_CURRENT_USER_SIGN_IN_ERROR",
  SET_CURRENT_USER_SIGN_UP_ERROR: "SET_CURRENT_USER_SIGN_UP_ERROR:",
};
export default userActionTypes;
